#http://localhost:8888/web/app_dev.php/immobilier/location/34000-montpellier
wegeoo_website_homepage:
    path:     /{pWegeooType}/{pCategoryLocaleName}/{pCityPostCode}-{pCityName}
    defaults: { _controller: WegeooWebsiteBundle:WegeooWebsiteHome:render, pWegeooType: property, pCategoryLocaleName:'', pCityPostCode:'', pCityName:'' }
    requirements:
            pCategoryLocaleName: "sale|rent|vente|location"

wegeoo_website_search:
    path:     /{pWegeooType}/{pCategoryLocaleName}/{pCityPostCode}-{pCityName}/search{map}/{pSearch}
    defaults: { _controller: WegeooWebsiteBundle:WegeooWebsiteHome:render, pWegeooType: property, pCategoryLocaleName:'', pCityPostCode:'', pCityName:'', map:'', pSearch:'' }
    requirements:
        map    : "@([-.0-9]*,[-.0-9]*,[0-9]*)"
        pSearch:  "[;+&=,a-zA-Z0-9]*"


wegeoo_website_classifiedpage:
    path:     /{wegeooType}/{categoryLocaleName}/{cityPostCode}-{cityName}/{reference}
    defaults: { _controller: WegeooWebsiteBundle:WegeooWebsiteClassified:render  }

wegeoo_website_publication:
    path:     /{wegeooType}/{post}
    defaults: { _controller: WegeooWebsiteBundle:WegeooWebsitePost:render , wegeooType: property , post: post }
    requirements:
        post    : "post|publication"

wegeoo_website_advertiser_offers:
    path:     /{wegeooType}/{advertisers}
    defaults: { _controller: WegeooWebsiteBundle:WegeooWebsiteAdvertiserOffers:render , wegeooType: property }
    requirements:
        post    : "annonceurs|advertisers"

wegeoo_website_activation:
    path:     /activ/{reference}/{activationCode}
    defaults: { _controller: WegeooWebsiteBundle:WegeooWebsiteClassifiedActivation:render }