parameters:
#    wegeoo_website.example.class: Wegeoo\WebsiteBundle\Example

services:
    wegeoo:
        class: Wegeoo\WebsiteBundle\Services\WegeooServices
        arguments: ["@service_container", "@router","@logger","@translator" , %wegeoo_type%]
    user_configuration:
        class: Wegeoo\WebsiteBundle\Services\UserConfiguration
        arguments: ["@logger"]
    date:
        class: Wegeoo\WebsiteBundle\Services\Date
        arguments: ["@logger","@translator"]

    wegeoo.type.classified:
         class: Wegeoo\WebsiteBundle\Form\Type\ClassifiedFormType
         arguments: ["@request=","@doctrine.orm.entity_manager" , "@translator"]
         tags:
            - { name: form.type, alias: classified_form }

    wegeoo.type.map:
        class: Wegeoo\WebsiteBundle\Form\Type\WegeooMapType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: wegeoo_map }

    wegeoo.type.mapaddress:
        class: Wegeoo\WebsiteBundle\Form\Type\WegeooMapAddressType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: wegeoo_map_address }

    wegeoo.type.citydropdown:
        class: Wegeoo\WebsiteBundle\Form\Type\CityListType
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: form.type, alias: city_list }

    wegeoo.type.wegeoocontact:
        class: Wegeoo\WebsiteBundle\Form\Type\ClassifiedContactType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: classified_contact }

    wegeoo.type.classified_details:
        class: Wegeoo\WebsiteBundle\Form\Type\ClassifiedDetailsType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: classified_details }

    wegeoo.type.classified_medias:
        class: Wegeoo\WebsiteBundle\Form\Type\ClassifiedMediasType
        arguments: ["@translator"]
        tags:
            - { name: form.type, alias: classified_medias }

    wegeoo.twig.wegeoo_extension:
        class: Wegeoo\WebsiteBundle\Twig\WegeooExtension
        arguments: [ %country% ]
        tags:
            - { name: twig.extension }