monolog:
    handlers:
        syslog:
            type: stream
            path: /var/log/symfony.log
            level: ERROR
            bubble: false

        main:
            type:         fingers_crossed
            action_level : ERROR
            handler:      nested
        nested:
            type:  stream
            path:  "%kernel.logs_dir%/%kernel.environment%.log"

framework:
    #esi:             ~
    translator:      { fallback: en }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  en
    trusted_proxies: ~
    session:         ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        date: "@date"
        locale: %locale%
        country: %country%
        wegeoo_type: %wegeoo_type%
    form:
        resources:
            - 'WegeooWebsiteBundle:Form:classified_form.html.twig'
            - 'WegeooWebsiteBundle:Form:wegeooMap.html.twig'
            - 'WegeooWebsiteBundle:Form:classified_map_address.html.twig'
            - 'WegeooWebsiteBundle:Form:city_list.html.twig'
            - 'WegeooWebsiteBundle:Form:classified_contact.html.twig'
            - 'WegeooWebsiteBundle:Form:classified_details.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles: ["WegeooWebsiteBundle"]
    filters:
        cssrewrite: ~
        less:
            node:       /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
            apply_to:   "\.less$"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver, add the path in parameters_prod.yml
        # e.g. database_path: "%kernel.root_dir%/data/data.db3"
        # path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    encryption: "%mailer_encryption%"
    auth_mode: "%mailer_auth_mode%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

fos_rest:
    routing_loader:
        default_format: json
    param_fetcher_listener: true

gregwar_captcha:
    quality: 100